from pathlib import Path
from collections import defaultdict

import numpy as np
import xarray as xr

import warnings
from dask.array import PerformanceWarning

warnings.simplefilter("ignore", FutureWarning)
warnings.filterwarnings(
    "ignore",
    category=PerformanceWarning,
)

from dask.diagnostics.progress import ProgressBar

from earthml import (
    LeadtimeUnit,
    ClimPeriod,
    get_experiment_configs,
    get_and_subset_datasets,
)
from earthml.metrics import (
    LeadtimeAgg,
    MetricAgg,
    is_deterministic,
    is_probabilistic,
    get_metrics,
    calculate_save_and_subset_climatologies,
    stack_hour_clim,
    groupby_period,
    build_metric_improvements,
    get_required_improvement_metrics,
)
from earthml.plots import (
    safe_label,
    PlotMode,
    plot_profile,
)


def get_profile_metrics(
    *,
    s,
    an,
    fc,
    an_clim,
    fc_clim,
    metrics,
    realization_agg,
    metric_agg_mode,
    leadtime_agg_mode,
    leadtime_agg_coord,
    clim_period,
    period_dim,
    wanted_start_periods,
):
    metric_kind = (
        "scalar"
        if metric_agg_mode == "global"
        else "maps"
    )

    ds = get_metrics(
        an=an,
        fc=fc,
        var=s.var_fc,
        metric_kind=metric_kind,
        leadtime_agg=leadtime_agg_mode,
        realization_agg=realization_agg,
        an_clim=an_clim,
        fc_clim=fc_clim,
        metrics=metrics,
        leadtime_windows=s.seasonal_leadtime_windows,
        leadtime_agg_coord=leadtime_agg_coord,
        clim_period=clim_period,
        period_dim=period_dim,
        periods_requested=wanted_start_periods,
    )

    if metric_agg_mode == "global":
        return ds

    if metric_agg_mode == "spatial_avg":
        lat_dim = fc.earthml.guessed_dims.latitude
        lon_dim = fc.earthml.guessed_dims.longitude

        weights = np.cos(np.deg2rad(fc[lat_dim]))

        return ds.weighted(weights).mean(
            dim=(lat_dim, lon_dim)
        )

    raise ValueError(
        f"Unsupported metric_agg_mode={metric_agg_mode!r}"
    )


def get_improvement_variant(
    comparison_name: str,
) -> str:
    """
    Extract the improvement representation from a model-comparison
    name generated by build_metric_improvements().
    """
    if comparison_name.endswith("_percentage"):
        return "percentage"

    if comparison_name.endswith("_difference"):
        return "difference"

    if comparison_name.endswith("_normalized"):
        return "normalized"

    raise ValueError(
        f"Cannot determine improvement representation "
        f"from comparison name {comparison_name!r}."
    )


def get_profile_ylim(
    profile_ylims: dict,
    metric: str,
    *,
    variant: str = "absolute",
) -> tuple[float, float] | None:
    """Return optional y-axis limits for a metric-profile variant."""
    return profile_ylims.get(variant, {}).get(metric)


def prepare_climatological_profile_da(
    da: xr.DataArray | None,
    *,
    period_dim: str,
    clim_period: ClimPeriod,
) -> xr.DataArray | None:
    """Prepare a metric DataArray for a climatological-period profile.

    The aggregate ``"all"`` period is removed. Month and day-of-year
    coordinates are converted to integers so ``plot_profile`` can format the
    climatological x axis correctly.
    """
    if da is None:
        return None

    if period_dim not in da.dims:
        raise ValueError(
            f"Climatological period dimension {period_dim!r} not found "
            f"in {da.dims}."
        )

    period_values = [
        value
        for value in da[period_dim].values
        if str(value) != "all"
    ]

    da = da.sel({period_dim: period_values})

    if clim_period in {
        ClimPeriod.MONTH,
        ClimPeriod.DAYOFYEAR,
    }:
        period_values = np.asarray(
            [int(value) for value in da[period_dim].values],
            dtype=int,
        )
        da = da.assign_coords({period_dim: period_values})

    return da


def get_climatological_profile_leadtimes(
    reference: xr.DataArray | xr.Dataset,
    *,
    leadtime_dim: str,
    wanted_leadtimes: list[object] | tuple[object, ...] | None,
) -> list[object]:
    """Return lead times to use as fixed values in climatological profiles."""
    available = list(reference[leadtime_dim].values)

    if wanted_leadtimes is None:
        return available

    wanted = {str(value) for value in wanted_leadtimes}

    return [
        value
        for value in available
        if str(value) in wanted
    ]

def main() -> None:

    # ==========================================================
    # Paths
    # ==========================================================

    experiments_root = Path(
        "/Users/jacopodallaglio/ML/training/seasonal/experiments_plots"
        # "/work/cmcc/jd19424/ML/MLBC/experiments/weather_atmo"
    )

    common_plot_dir = Path(
        "/Users/jacopodallaglio/ML/training/seasonal/plots"
        # "/work/cmcc/jd19424/ML/MLBC/plots/weather_atmo/common"
    )

    # ==========================================================
    # Plot settings
    # ==========================================================

    plot_mode: PlotMode = "profiles"

    plot_title = True
    title_strftime = "%Y" # seasonal
    # title_strftime = "%m.%Y" # weather

    # Optional y-axis limits by profile representation and metric.
    # Missing metrics (or explicit None values) use automatic limits.
    profile_ylims = {
        "absolute": {
            # day of year clim
            # "bias": (-1, 1),
            # "rmse": (0, 2),
            # "corr": (0.5, 1.0),
            # monthly clim
            "bias": (-0.5, 0.5),
            "rmse": (0.5, 1.8),
            "corr": (0.5, 1.0),
        },
        "percentage": {
            # "rmse": (-50, 50),
        },
        "difference": {
            # "rmse": (-1, 1),
        },
        "normalized": {
            # "rmse": (-1, 1),
        },
    }

    plot_individual_experiments = True
    plot_combined_experiments = False

    plot_members = False

    # Profile orientation.
    #
    # Lead-time profile:
    #   x = lead time, one curve for a selected climatological start period
    #
    # Climatological profile:
    #   x = climatological period (e.g. month), one curve for a selected
    #   lead time.
    plot_leadtime_profiles = True
    plot_climatological_profiles = True

    # None -> create one climatological profile for every available lead time
    # wanted_climatological_profile_leadtimes = [24, 48, 72,]
    # wanted_climatological_profile_leadtimes = [72,]
    wanted_climatological_profile_leadtimes = None

    regenerate_plots = False

    # ==========================================================
    # Model settings
    # ==========================================================

    include_clim_fc = True

    model_comparisons = (
        ("fc", "mlfc"),
        # ("clim-fc", "mlfc"),
        # ("fc", "clim-fc"),
    )

    # ==========================================================
    # Combined experiment settings
    # ==========================================================

    combined_plot_folder = "profile_comparison"

    comparison_name = (
        "smaatunet-convnexttransformer"
    )

    comparison_labels = [
        "ConvNeXt reanalysis",
        "ConvNeXt reanalysis ens mean",
        "SmaAt-UNet anomaly residual ens mean",
        "SmaAt-UNet anomaly residual",
    ]

    comparison_colors = {
        "fc": "tab:blue",
        "clim-fc": "tab:orange",

        "ConvNeXt reanalysis": "green",
        "ConvNeXt reanalysis ens mean": "green",

        "SmaAt-UNet anomaly residual ens mean": "red",
        "SmaAt-UNet anomaly residual": "red",
    }

    comparison_linestyles = {
        "fc": "-",
        "clim-fc": "-",

        "ConvNeXt reanalysis": "-",
        "ConvNeXt reanalysis ens mean": "--",

        "SmaAt-UNet anomaly residual ens mean": "--",
        "SmaAt-UNet anomaly residual": "-",
    }

    # ==========================================================
    # Data processing
    # ==========================================================

    interpolate = True # seasonal
    # interpolate = False # weather
    build_analysis = True

    recalculate_climatology = False

    # Compute metric datasets once before repeated plotting.
    materialize_once = False

    # ==========================================================
    # Climatology
    # ==========================================================

    clim_period: ClimPeriod = ClimPeriod.MONTH
    clim_rolling_window = None

    # clim_period: ClimPeriod = ClimPeriod.DAYOFYEAR_HOUR
    # clim_rolling_window = 31

    # clim_period: ClimPeriod = ClimPeriod.DAYOFYEAR
    # clim_rolling_window = None

    # ==========================================================
    # Time selection
    # ==========================================================

    time_range = None
    # time_range = ("2018-01-01", "2022-12-31")

    inference_period = None
    # inference_period = ("2025-01-01", "2025-10-31")

    wanted_start_periods = [
        "01",
        "02",
        "03",
        "04",
        "05",
        "06",
        "07",
        "08",
        "09",
        "10",
        "11",
        "12",
        "all",
    ]

    # ==========================================================
    # Metric aggregation
    # ==========================================================

    metric_agg_mode: MetricAgg = "spatial_avg"
    # "spatial_avg"
    # "global"

    leadtime_agg_mode: LeadtimeAgg = "aggregated"
    # "single" for weather
    # "aggregated" for seasonal
    # "seasonal_window"

    leadtime_units = LeadtimeUnit.MONTHS # seasonal
    # leadtime_units = LeadtimeUnit.HOURS # weather

    # ==========================================================
    # Metrics
    # ==========================================================

    metrics = [
        # ======================================================
        # Deterministic metrics - absolute fields
        # ======================================================
        "bias",
        # "mae",
        # "mse",
        "rmse",
        # "nrmse",
        # "corr",
        # "r2",
        # "fc_std",
        # "an_std",
        # "std_ratio",

        # Gradient metrics
        # "fc_grad_mag",
        # "an_grad_mag",
        # "grad_rmse",

        # MSE decomposition / calibration diagnostics
        # "mse_bias_component",
        # "mse_std_component",
        # "mse_corr_component",
        # "crmse",
        # "regression_slope",

        # ======================================================
        # Deterministic metrics - anomaly fields
        # ======================================================
        # "bias_anom",
        # "mae_anom",
        # "mse_anom",
        # "rmse_anom",
        # "nrmse_anom",
        # "acc",
        # "r2_anom",
        # "fc_anom_std",
        # "an_anom_std",
        # "std_ratio_anom",

        # Gradient metrics
        # "fc_anom_grad_mag",
        # "an_anom_grad_mag",
        # "grad_rmse_anom",

        # Anomaly MSE decomposition / calibration diagnostics
        # "mse_bias_component_anom",
        # "mse_std_component_anom",
        # "mse_corr_component_anom",
        # "crmse_anom",
        # "regression_slope_anom",

        # ======================================================
        # Skill scores vs climatology
        # ======================================================
        # "mse_skill_clim",
        # "mae_anom_skill_clim",
        # "mse_anom_skill_clim",
        # "rmse_anom_skill_clim",
        # "ens_member_mse_anom_skill_clim",
        # "mean_member_mse_anom_skill_clim",

        # ======================================================
        # Ensemble / probabilistic metrics - absolute fields
        # ======================================================
        # "ens_member_rmse",
        # "mean_member_rmse",
        # "spread",
        # "spread_skill_ratio",
        # "crps",
        # "rank_histogram",

        # ======================================================
        # Ensemble / probabilistic metrics - anomaly fields
        # ======================================================
        # "ens_member_rmse_anom",
        # "mean_member_rmse_anom",
        # "spread_anom",
        # "spread_anom_skill_ratio",
        # "crps_anom",
        # "rank_histogram_anom",

        # ======================================================
        # ROC AUC - anomaly terciles
        # ======================================================
        # "roc_anom_lower",
        # "roc_anom_middle",
        # "roc_anom_upper",
    ]

    # ==========================================================
    # Variables and regions
    # ==========================================================

    variables = [
        # Atmosphere
        # "mslp",
        "t2m",
        # "d2m",
        # "u10",
        # "v10",
        # "sst",
        # "tprate",
        # "tcc",

        # Ocean
        # "mlotst",
        # "ssh",
        # "sss",
        # "t20d",
    ]

    regions = [
        # "ConUS",
        # "Europe",
        # "Pacific",
        "World",
        # None,
    ]

    # ==========================================================
    # Spatial subset
    # ==========================================================

    # ConUS
    # lat_range = (50, 25)
    # lon_range = (-130, -60)

    # Europe
    # lat_range = (80, 30)
    # lon_range = (-30, 60)

    # Pacific
    # lat_range = (20, -20)
    # lon_range = (-195, -135)

    # Whole configured region
    lat_range = None
    lon_range = None

    # ==========================================================
    # Experiment selection
    # ==========================================================

    settings = get_experiment_configs(
        experiments_root,
        var_fc=variables,
        region_name=regions,

        # net_name="ConvNeXtTransformerUNet",
        net_name="SmaAt_UNet",

        target_mode="analysis",

        # seasonal_encoding=True,
        # ensemble_encoding=True,
        # input_realization_avg=True,
        # channel_representation="variable",

        loss_name="GeoMaskedMSELoss",
        # loss_name="GeoMaskedMSEMultiScaleLoss",
        # loss_name="SpatialDegradationMSELoss",

        # separate_training_by_init_period=None,
        # separate_training_by_init_period=ClimPeriod.MONTH,
        # pretrain_norm="full",

        # extra_suffix_folder="264samples_consecutive",
        # extra_suffix_folder="NOAA_copy",
        extra_suffix_folder="",
    )

    print(f"Found {len(settings)} matching experiment(s).")

    # Add auxiliary metrics required for improvement
    # representations, e.g. standard deviation for normalized
    # improvements.
    metrics_to_compute = get_required_improvement_metrics(
        list(metrics)
    )

    # ==========================================================
    # Configuration validation
    # ==========================================================

    if not include_clim_fc:
        invalid_comparisons = [
            comparison
            for comparison in model_comparisons
            if "clim-fc" in comparison
        ]

        if invalid_comparisons:
            raise ValueError(
                "model_comparisons contains clim-fc while "
                "include_clim_fc=False: "
                f"{invalid_comparisons}"
            )

    # ==========================================================
    # Combined-experiment storage
    # ==========================================================

    combined_groups = defaultdict(
        lambda: {
            "fc": None,
            "fc_members": None,
            "clim-fc": None,
            "clim-fc_members": None,
            "mlfc": [],
            "mlfc_members": [],
            "labels": [],
            "settings": [],
            "valid_time_range": None,
            "valid_lat_range": None,
            "valid_lon_range": None,
            "period_dim": None,
            "leadtime_agg_coord": None,
        }
    )

    n = 0

    # ==========================================================
    # Experiments
    # ==========================================================

    for s in settings:

        # ======================================================
        # Time range
        # ======================================================

        if inference_period is None:
            valid_time_range = (
                (s.test_start, s.test_end)
                # (s.train_start, s.train_end)
                if time_range is None
                else time_range
            )

            mlfc_path = None

        else:
            valid_time_range = (
                inference_period
                if time_range is None
                else time_range
            )

            inference_start, inference_end = inference_period

            mlfc_path = (
                s.exp_dir
                / "inference"
                / f"{inference_start}_{inference_end}"
                / "test_corrected.zarr"
            )

        # clim_time_range = (s.train_start, s.val_end) # weather (very few years)
        clim_time_range = (s.train_start, s.train_end) # seasonal

        # ======================================================
        # Spatial range
        # ======================================================

        lat_lon = (
            list(s.region.values())
            if s.region is not None
            else [None, None]
        )

        valid_lat_range = (
            lat_lon[0]
            if lat_range is None
            else lat_range
        )

        valid_lon_range = (
            lat_lon[1]
            if lon_range is None
            else lon_range
        )

        # ======================================================
        # Dimension names
        # ======================================================

        leadtime_agg_coord = (
            "leadtime"
            if leadtime_agg_mode == "single"
            else "leadtime_seasonal"
        )

        period_dim = f"start_{clim_period}"

        print(
            f"Generate {leadtime_agg_mode} {plot_mode} "
            f"for {(s.var_an, s.var_fc)} in {s.region_name} "
            f"(lon={valid_lon_range}, lat={valid_lat_range})"
        )

        # ======================================================
        # Data
        # ======================================================

        fc, an, mlfc = get_and_subset_datasets(
            s,
            leadtime_units=leadtime_units,
            lat_range=valid_lat_range,
            lon_range=valid_lon_range,
            time_range=valid_time_range,
            interpolate=interpolate,
            mlfc_path=mlfc_path,
        )

        if mlfc is not None:
            mlfc = mlfc.assign_coords(
                leadtime=s.leadtimes
            )

        # ======================================================
        # Climatologies
        # ======================================================

        fc_clim, an_clim, mlfc_clim = (
            calculate_save_and_subset_climatologies(
                s,
                leadtime_units=leadtime_units,
                force=recalculate_climatology,
                clim_period=clim_period,
                rolling_window=clim_rolling_window,
                rolling_center=True,
                rolling_min_periods=1,
                lat_range=valid_lat_range,
                lon_range=valid_lon_range,
                time_range=clim_time_range,
                time_start=None,
                interpolate=interpolate,
                engine="zarr",
                build_analysis=build_analysis,
                coord_rename_fc=None,
                coord_rename_an=None,
            )
        )

        if mlfc_clim is not None:
            mlfc_clim = mlfc_clim.assign_coords(
                leadtime=s.leadtimes
            )

        # ======================================================
        # Lead-time subset
        # ======================================================

        leadtime_dim = fc.earthml.guessed_dims.leadtime

        fc = fc.sel(
            {leadtime_dim: s.leadtimes}
        )

        an = an.sel(
            {leadtime_dim: s.leadtimes}
        )

        fc_clim = fc_clim.sel(
            {leadtime_dim: s.leadtimes}
        )

        an_clim = an_clim.sel(
            {leadtime_dim: s.leadtimes}
        )

        # ======================================================
        # Climatology-corrected forecast
        # ======================================================

        fc_clim_da = stack_hour_clim(
            fc_clim[s.var_fc],
            clim_period,
        )

        an_clim_da = stack_hour_clim(
            an_clim[s.var_an],
            clim_period,
        )

        fc_anom_da = (
            groupby_period(
                fc[s.var_fc],
                fc.earthml.guessed_dims.time,
                clim_period,
            )
            - fc_clim_da
        )

        clim_fc = (
            groupby_period(
                fc_anom_da,
                fc.earthml.guessed_dims.time,
                clim_period,
            )
            + an_clim_da
        ).to_dataset(
            name=s.var_fc
        )


        # ======================================================
        # Climatology realization handling
        # ======================================================

        an_clim_for_fc = an_clim

        realization_dim = (
            fc.earthml.guessed_dims.realization
        )

        if (
            realization_dim is not None
            and realization_dim in fc.dims
            and realization_dim not in an_clim_for_fc.dims
        ):
            an_clim_for_fc = (
                an_clim_for_fc.expand_dims(
                    {
                        realization_dim:
                            fc[realization_dim]
                    }
                )
            )

        # ======================================================
        # Available models
        # ======================================================

        datasets = {
            "fc": (
                fc,
                fc_clim,
            ),
            "mlfc": (
                mlfc,
                mlfc_clim,
            ),
        }

        if include_clim_fc:
            datasets["clim-fc"] = (
                clim_fc,
                an_clim_for_fc,
            )


        if plot_mode not in {
            "profiles",
            "all",
        }:
            continue

        # ======================================================
        # Metrics to compute
        # ======================================================

        deterministic_metrics = [
            metric
            for metric in metrics_to_compute
            if is_deterministic(metric)
        ]

        probabilistic_metrics = [
            metric
            for metric in metrics_to_compute
            if is_probabilistic(metric)
        ]


        metrics_by_model: dict[
            str,
            xr.Dataset,
        ] = {}

        members_by_model: dict[
            str,
            xr.Dataset,
        ] = {}

        # ======================================================
        # Compute metrics
        # ======================================================

        for model, (
            ds,
            ds_clim,
        ) in datasets.items():

            if ds is None or ds_clim is None:
                continue

            print(
                f"Get {model} profile metrics"
            )

            metric_parts = []

            # --------------------------------------------------
            # Deterministic / ensemble-mean metrics
            # --------------------------------------------------

            if deterministic_metrics:
                metric_parts.append(
                    get_profile_metrics(
                        s=s,
                        an=an,
                        fc=ds,
                        an_clim=an_clim,
                        fc_clim=ds_clim,
                        metrics=deterministic_metrics,
                        realization_agg=True,
                        metric_agg_mode=metric_agg_mode,
                        leadtime_agg_mode=leadtime_agg_mode,
                        leadtime_agg_coord=leadtime_agg_coord,
                        clim_period=clim_period,
                        period_dim=period_dim,
                        wanted_start_periods=wanted_start_periods,
                    )
                )

            # --------------------------------------------------
            # Probabilistic metrics
            # --------------------------------------------------

            if probabilistic_metrics:
                metric_parts.append(
                    get_profile_metrics(
                        s=s,
                        an=an,
                        fc=ds,
                        an_clim=an_clim,
                        fc_clim=ds_clim,
                        metrics=probabilistic_metrics,
                        realization_agg=False,
                        metric_agg_mode=metric_agg_mode,
                        leadtime_agg_mode=leadtime_agg_mode,
                        leadtime_agg_coord=leadtime_agg_coord,
                        clim_period=clim_period,
                        period_dim=period_dim,
                        wanted_start_periods=wanted_start_periods,
                    )
                )

            if metric_parts:
                metrics_by_model[model] = xr.merge(
                    metric_parts
                )

            # --------------------------------------------------
            # Individual-member deterministic metrics
            # --------------------------------------------------

            if (
                plot_members
                and deterministic_metrics
            ):
                members_by_model[model] = (
                    get_profile_metrics(
                        s=s,
                        an=an,
                        fc=ds,
                        an_clim=an_clim,
                        fc_clim=ds_clim,
                        metrics=deterministic_metrics,
                        realization_agg=False,
                        metric_agg_mode=metric_agg_mode,
                        leadtime_agg_mode=leadtime_agg_mode,
                        leadtime_agg_coord=leadtime_agg_coord,
                        clim_period=clim_period,
                        period_dim=period_dim,
                        wanted_start_periods=wanted_start_periods,
                    )
                )

        if not metrics_by_model:
            print(
                f"No metrics available for "
                f"{s.output_name}"
            )
            continue

        # ======================================================
        # Optional materialization
        # ======================================================

        if materialize_once:
            with ProgressBar():

                metrics_by_model = {
                    model: ds.compute()
                    for model, ds
                    in metrics_by_model.items()
                }

                members_by_model = {
                    model: ds.compute()
                    for model, ds
                    in members_by_model.items()
                }

        # ======================================================
        # Available start periods
        # ======================================================

        reference_ds = next(
            iter(metrics_by_model.values())
        )

        start_periods = [
            str(value)
            for value in reference_ds[
                period_dim
            ].values
            if str(value) in wanted_start_periods
        ]

        leadtime_profile_periods = (
            start_periods
            if plot_leadtime_profiles
            else []
        )

        climatological_profile_leadtimes = (
            get_climatological_profile_leadtimes(
                reference_ds,
                leadtime_dim=leadtime_agg_coord,
                wanted_leadtimes=(
                    wanted_climatological_profile_leadtimes
                ),
            )
            if plot_climatological_profiles
            else []
        )

        # ======================================================
        # Individual experiment plots
        # ======================================================

        if plot_individual_experiments:

            # ==================================================
            # Absolute profiles
            # ==================================================

            available_models = tuple(
                model
                for model in datasets
                if model in metrics_by_model
            )

            available_metrics = [
                metric
                for metric in metrics
                if (
                    metric != "rank_histogram"
                    and all(
                        metric
                        in metrics_by_model[
                            model
                        ]
                        for model
                        in available_models
                    )
                )
            ]

            print(
                f"Plotting absolute metric profiles "
                f"{available_metrics} "
                f"for periods {start_periods} "
                f"for exp {s.output_name}"
            )

            for metric in available_metrics:

                das = [
                    metrics_by_model[
                        model
                    ][metric]
                    for model
                    in available_models
                ]

                das_member = []

                for model in available_models:
                    member_ds = (
                        members_by_model.get(
                            model
                        )
                    )

                    if (
                        member_ds is not None
                        and metric in member_ds
                    ):
                        das_member.append(
                            member_ds[metric]
                        )

                    else:
                        das_member.append(None)


                for start_period in leadtime_profile_periods:

                    common_path = (
                        Path("profiles")
                        / "absolute"
                        / safe_label(
                            start_period
                        )
                        / (
                            f"time_"
                            f"{safe_label(valid_time_range)}"
                            f"_lat_"
                            f"{safe_label(valid_lat_range)}"
                            f"_lon_"
                            f"{safe_label(valid_lon_range)}"
                        )
                        / metric
                        / metric_agg_mode
                    )

                    filename = (
                        f"{s.var_fc}_"
                        f"{metric}_"
                        f"{leadtime_agg_mode}lt.png"
                    )

                    out_file = (
                        s.plot_dir
                        / common_path
                        / filename
                    )

                    if (
                        out_file.exists()
                        and not regenerate_plots
                    ):
                        continue

                    print(
                        f"Saving profile "
                        f"{out_file}"
                    )

                    plot_profile(
                        das=das,
                        var=s.var_fc,
                        metric=metric,
                        select_value=start_period,
                        models=available_models,
                        out_file=out_file,
                        time_range=valid_time_range,
                        das_member=das_member,
                        profile_dim=leadtime_agg_coord,
                        profile_unit=leadtime_units,
                        select_dim=period_dim,
                        select_unit=clim_period.value,
                        realization_dim="realization",
                        spread="std",
                        plot_single_members=plot_members,
                        plot_title=plot_title,
                        title_strftime=title_strftime,
                        ylim=get_profile_ylim(
                            profile_ylims,
                            metric,
                            variant="absolute",
                        ),
                    )

                    n += 1

                # ----------------------------------------------
                # Climatological-period profile
                # ----------------------------------------------

                if plot_climatological_profiles:
                    climatological_das = [
                        prepare_climatological_profile_da(
                            da,
                            period_dim=period_dim,
                            clim_period=clim_period,
                        )
                        for da in das
                    ]

                    climatological_das_member = [
                        prepare_climatological_profile_da(
                            da,
                            period_dim=period_dim,
                            clim_period=clim_period,
                        )
                        for da in das_member
                    ]

                    for lead_value in climatological_profile_leadtimes:

                        common_path = (
                            Path("profiles")
                            / "climatology"
                            / "absolute"
                            / f"leadtime_{safe_label(lead_value)}"
                            / (
                                f"time_"
                                f"{safe_label(valid_time_range)}"
                                f"_lat_"
                                f"{safe_label(valid_lat_range)}"
                                f"_lon_"
                                f"{safe_label(valid_lon_range)}"
                            )
                            / metric
                            / metric_agg_mode
                        )

                        filename = (
                            f"{s.var_fc}_"
                            f"{metric}_"
                            f"{safe_label(period_dim)}_"
                            f"leadtime_{safe_label(lead_value)}.png"
                        )

                        out_file = (
                            s.plot_dir
                            / common_path
                            / filename
                        )

                        if (
                            out_file.exists()
                            and not regenerate_plots
                        ):
                            continue

                        print(
                            "Saving climatological profile "
                            f"{out_file}"
                        )

                        plot_profile(
                            das=climatological_das,
                            var=s.var_fc,
                            metric=metric,
                            models=available_models,
                            out_file=out_file,
                            time_range=valid_time_range,
                            das_member=climatological_das_member,
                            profile_dim=period_dim,
                            profile_unit=clim_period.value,
                            select_dim=leadtime_agg_coord,
                            select_value=lead_value,
                            select_unit=leadtime_units.value,
                            realization_dim="realization",
                            spread="std",
                            plot_single_members=plot_members,
                            plot_title=plot_title,
                            title_strftime=title_strftime,
                            ylim=get_profile_ylim(
                                profile_ylims,
                                metric,
                                variant="absolute",
                            ),
                        )

                        n += 1

            # ==================================================
            # Model-comparison profiles
            # ==================================================

            for (
                baseline_model,
                target_model,
            ) in model_comparisons:

                if (
                    baseline_model
                    not in metrics_by_model
                ):
                    continue

                if (
                    target_model
                    not in metrics_by_model
                ):
                    continue

                baseline_ds = (
                    metrics_by_model[
                        baseline_model
                    ]
                )

                target_ds = (
                    metrics_by_model[
                        target_model
                    ]
                )

                comparison_metrics = [
                    metric
                    for metric in metrics
                    if (
                        metric != "rank_histogram"
                        and metric in baseline_ds
                        and metric in target_ds
                    )
                ]

                for metric in comparison_metrics:

                    improvements = (
                        build_metric_improvements(
                            baseline_ds,
                            target_ds,
                            metric=metric,
                            baseline_model=baseline_model,
                            target_model=target_model,
                        )
                    )

                    for (
                        comparison_model,
                        comparison_da,
                    ) in improvements.items():

                        for start_period in leadtime_profile_periods:

                            common_path = (
                                Path("profiles")
                                / "comparisons"
                                / safe_label(
                                    comparison_model
                                )
                                / safe_label(
                                    start_period
                                )
                                / (
                                    f"time_"
                                    f"{safe_label(valid_time_range)}"
                                    f"_lat_"
                                    f"{safe_label(valid_lat_range)}"
                                    f"_lon_"
                                    f"{safe_label(valid_lon_range)}"
                                )
                                / metric
                                / metric_agg_mode
                            )

                            filename = (
                                f"{s.var_fc}_"
                                f"{metric}_"
                                f"{safe_label(comparison_model)}_"
                                f"{leadtime_agg_mode}lt.png"
                            )

                            out_file = (
                                s.plot_dir
                                / common_path
                                / filename
                            )

                            if (
                                out_file.exists()
                                and not regenerate_plots
                            ):
                                continue

                            print(
                                "Saving comparison "
                                f"profile {out_file}"
                            )

                            plot_profile(
                                das=[
                                    comparison_da
                                ],
                                var=s.var_fc,
                                metric=metric,
                                models=(
                                    comparison_model,
                                ),
                                out_file=out_file,
                                time_range=valid_time_range,
                                das_member=[None],
                                profile_dim=leadtime_agg_coord,
                                profile_unit=leadtime_units,
                                select_value=start_period,
                                select_dim=period_dim,
                                select_unit=clim_period.value,
                                realization_dim="realization",
                                spread="std",
                                plot_single_members=False,
                                plot_title=plot_title,
                                title_strftime=title_strftime,
                                ylim=get_profile_ylim(
                                    profile_ylims,
                                    metric,
                                    variant=get_improvement_variant(
                                        comparison_model
                                    ),
                                ),
                            )

                            n += 1

                        # --------------------------------------
                        # Climatological-period profile
                        # --------------------------------------

                        if plot_climatological_profiles:
                            climatological_comparison_da = (
                                prepare_climatological_profile_da(
                                    comparison_da,
                                    period_dim=period_dim,
                                    clim_period=clim_period,
                                )
                            )

                            for (
                                lead_value
                            ) in climatological_profile_leadtimes:

                                common_path = (
                                    Path("profiles")
                                    / "climatology"
                                    / "comparisons"
                                    / safe_label(
                                        comparison_model
                                    )
                                    / (
                                        f"leadtime_"
                                        f"{safe_label(lead_value)}"
                                    )
                                    / (
                                        f"time_"
                                        f"{safe_label(valid_time_range)}"
                                        f"_lat_"
                                        f"{safe_label(valid_lat_range)}"
                                        f"_lon_"
                                        f"{safe_label(valid_lon_range)}"
                                    )
                                    / metric
                                    / metric_agg_mode
                                )

                                filename = (
                                    f"{s.var_fc}_"
                                    f"{metric}_"
                                    f"{safe_label(comparison_model)}_"
                                    f"{safe_label(period_dim)}_"
                                    f"leadtime_"
                                    f"{safe_label(lead_value)}.png"
                                )

                                out_file = (
                                    s.plot_dir
                                    / common_path
                                    / filename
                                )

                                if (
                                    out_file.exists()
                                    and not regenerate_plots
                                ):
                                    continue

                                print(
                                    "Saving climatological "
                                    "comparison profile "
                                    f"{out_file}"
                                )

                                plot_profile(
                                    das=[
                                        climatological_comparison_da
                                    ],
                                    var=s.var_fc,
                                    metric=metric,
                                    models=(
                                        comparison_model,
                                    ),
                                    out_file=out_file,
                                    time_range=valid_time_range,
                                    das_member=[None],
                                    profile_dim=period_dim,
                                    profile_unit=None,
                                    select_dim=leadtime_agg_coord,
                                    select_value=lead_value,
                                    select_unit=leadtime_units.value,
                                    realization_dim="realization",
                                    spread="std",
                                    plot_single_members=False,
                                    plot_title=plot_title,
                                    title_strftime=title_strftime,
                                    ylim=get_profile_ylim(
                                        profile_ylims,
                                        metric,
                                        variant=get_improvement_variant(
                                            comparison_model
                                        ),
                                    ),
                                )

                                n += 1

        # ======================================================
        # Accumulate combined experiments
        # ======================================================

        if (
            plot_combined_experiments
            and "mlfc" in metrics_by_model
        ):
            comparison_key = (
                s.var_fc,
                s.region_name,
                safe_label(
                    valid_time_range
                ),
                safe_label(
                    valid_lat_range
                ),
                safe_label(
                    valid_lon_range
                ),
                tuple(s.leadtimes),
                leadtime_agg_mode,
                metric_agg_mode,
                str(clim_period),
            )

            group = combined_groups[
                comparison_key
            ]

            group[
                "valid_time_range"
            ] = valid_time_range

            group[
                "valid_lat_range"
            ] = valid_lat_range

            group[
                "valid_lon_range"
            ] = valid_lon_range

            group[
                "period_dim"
            ] = period_dim

            group[
                "leadtime_agg_coord"
            ] = leadtime_agg_coord


            # FC is common to experiments in the same group.
            if (
                group["fc"] is None
                and "fc" in metrics_by_model
            ):
                group["fc"] = (
                    metrics_by_model["fc"]
                )

                group["fc_members"] = (
                    members_by_model.get(
                        "fc"
                    )
                )

            if (
                include_clim_fc
                and group["clim-fc"] is None
                and "clim-fc"
                in metrics_by_model
            ):
                group["clim-fc"] = (
                    metrics_by_model[
                        "clim-fc"
                    ]
                )

                group[
                    "clim-fc_members"
                ] = members_by_model.get(
                    "clim-fc"
                )

            group["mlfc"].append(
                metrics_by_model[
                    "mlfc"
                ]
            )

            group[
                "mlfc_members"
            ].append(
                members_by_model.get(
                    "mlfc"
                )
            )

            group["labels"].append(
                s.output_name
            )

            group["settings"].append(
                s
            )

    # ==========================================================
    # Combined experiment profile plots
    # ==========================================================

    if plot_combined_experiments:

        for (
            comparison_key,
            group,
        ) in combined_groups.items():

            if not group["mlfc"]:
                continue

            common_s = (
                group["settings"][0]
            )

            valid_time_range = (
                group[
                    "valid_time_range"
                ]
            )

            valid_lat_range = (
                group[
                    "valid_lat_range"
                ]
            )

            valid_lon_range = (
                group[
                    "valid_lon_range"
                ]
            )

            period_dim = (
                group["period_dim"]
            )

            leadtime_agg_coord = (
                group[
                    "leadtime_agg_coord"
                ]
            )

            # ==================================================
            # Build combined model dictionary
            # ==================================================

            das_by_model: dict[
                str,
                xr.Dataset,
            ] = {}

            members_by_combined_model: dict[
                str,
                xr.Dataset,
            ] = {}


            if group["fc"] is not None:
                das_by_model["fc"] = (
                    group["fc"]
                )

                if (
                    group["fc_members"]
                    is not None
                ):
                    members_by_combined_model[
                        "fc"
                    ] = group[
                        "fc_members"
                    ]

            if (
                include_clim_fc
                and group["clim-fc"]
                is not None
            ):
                das_by_model[
                    "clim-fc"
                ] = group[
                    "clim-fc"
                ]

                if (
                    group[
                        "clim-fc_members"
                    ]
                    is not None
                ):
                    members_by_combined_model[
                        "clim-fc"
                    ] = group[
                        "clim-fc_members"
                    ]

            if (
                len(comparison_labels)
                != len(group["mlfc"])
            ):
                raise ValueError(
                    "comparison_labels must contain "
                    "one label for each combined "
                    "experiment. "
                    f"Got {len(comparison_labels)} "
                    f"labels for "
                    f"{len(group['mlfc'])} "
                    "experiments."
                )

            for (
                experiment_label,
                mlfc_metrics,
                mlfc_members,
            ) in zip(
                comparison_labels,
                group["mlfc"],
                group["mlfc_members"],
                strict=True,
            ):
                das_by_model[
                    experiment_label
                ] = mlfc_metrics

                if mlfc_members is not None:
                    members_by_combined_model[
                        experiment_label
                    ] = mlfc_members

            # ==================================================
            # Available periods
            # ==================================================

            reference_ds = next(
                iter(das_by_model.values())
            )

            start_periods = [
                str(value)
                for value
                in reference_ds[
                    period_dim
                ].values
                if str(value)
                in wanted_start_periods
            ]

            leadtime_profile_periods = (
                start_periods
                if plot_leadtime_profiles
                else []
            )

            climatological_profile_leadtimes = (
                get_climatological_profile_leadtimes(
                    reference_ds,
                    leadtime_dim=leadtime_agg_coord,
                    wanted_leadtimes=wanted_climatological_profile_leadtimes,
                )
                if plot_climatological_profiles
                else []
            )

            # ==================================================
            # Absolute combined profiles
            # ==================================================

            available_models = tuple(
                das_by_model
            )

            available_metrics = [
                metric
                for metric in metrics
                if (
                    metric != "rank_histogram"
                    and all(
                        metric
                        in das_by_model[
                            model
                        ]
                        for model
                        in available_models
                    )
                )
            ]

            print(
                "Plotting combined experiment "
                f"profiles {available_metrics} "
                f"for periods {start_periods}: "
                f"{group['labels']}"
            )

            for metric in available_metrics:

                das = [
                    das_by_model[
                        model
                    ][metric]
                    for model
                    in available_models
                ]

                das_member = []

                for model in available_models:

                    member_ds = (
                        members_by_combined_model.get(
                            model
                        )
                    )

                    if (
                        member_ds is not None
                        and metric in member_ds
                    ):
                        das_member.append(
                            member_ds[metric]
                        )

                    else:
                        das_member.append(None)

                for start_period in leadtime_profile_periods:

                    common_path = (
                        Path("profiles")
                        / combined_plot_folder
                        / comparison_name
                        / "absolute"
                        / safe_label(
                            start_period
                        )
                        / (
                            f"time_"
                            f"{safe_label(valid_time_range)}"
                            f"_lat_"
                            f"{safe_label(valid_lat_range)}"
                            f"_lon_"
                            f"{safe_label(valid_lon_range)}"
                        )
                        / metric
                        / metric_agg_mode
                    )

                    filename = (
                        f"{common_s.var_fc}_"
                        f"{metric}_"
                        f"{leadtime_agg_mode}lt.png"
                    )

                    out_file = (
                        common_plot_dir
                        / common_path
                        / filename
                    )

                    if (
                        out_file.exists()
                        and not regenerate_plots
                    ):
                        continue

                    print(
                        "Saving combined profile "
                        f"{out_file}"
                    )

                    plot_profile(
                        das=das,
                        var=common_s.var_fc,
                        metric=metric,
                        models=available_models,
                        out_file=out_file,
                        time_range=valid_time_range,
                        das_member=das_member,
                        profile_dim=leadtime_agg_coord,
                        profile_unit=leadtime_units,
                        select_value=start_period,
                        select_dim=period_dim,
                        select_unit=clim_period.value,
                        realization_dim="realization",
                        spread="std",
                        plot_single_members=plot_members,
                        plot_title=plot_title,
                        title_strftime=title_strftime,
                        model_colors=comparison_colors,
                        model_linestyles=comparison_linestyles,
                        ylim=get_profile_ylim(
                            profile_ylims,
                            metric,
                            variant="absolute",
                        ),
                    )

                    n += 1

                # ----------------------------------------------
                # Climatological-period profile
                # ----------------------------------------------

                if plot_climatological_profiles:
                    climatological_das = [
                        prepare_climatological_profile_da(
                            da,
                            period_dim=period_dim,
                            clim_period=clim_period,
                        )
                        for da in das
                    ]

                    climatological_das_member = [
                        prepare_climatological_profile_da(
                            da,
                            period_dim=period_dim,
                            clim_period=clim_period,
                        )
                        for da in das_member
                    ]

                    for lead_value in climatological_profile_leadtimes:

                        common_path = (
                            Path("profiles")
                            / combined_plot_folder
                            / comparison_name
                            / "climatology"
                            / "absolute"
                            / f"leadtime_{safe_label(lead_value)}"
                            / (
                                f"time_"
                                f"{safe_label(valid_time_range)}"
                                f"_lat_"
                                f"{safe_label(valid_lat_range)}"
                                f"_lon_"
                                f"{safe_label(valid_lon_range)}"
                            )
                            / metric
                            / metric_agg_mode
                        )

                        filename = (
                            f"{common_s.var_fc}_"
                            f"{metric}_"
                            f"{safe_label(period_dim)}_"
                            f"leadtime_{safe_label(lead_value)}.png"
                        )

                        out_file = (
                            common_plot_dir
                            / common_path
                            / filename
                        )

                        if (
                            out_file.exists()
                            and not regenerate_plots
                        ):
                            continue

                        print(
                            "Saving combined climatological "
                            f"profile {out_file}"
                        )

                        plot_profile(
                            das=climatological_das,
                            var=common_s.var_fc,
                            metric=metric,
                            models=available_models,
                            out_file=out_file,
                            time_range=valid_time_range,
                            das_member=climatological_das_member,
                            profile_dim=period_dim,
                            profile_unit=None,
                            select_dim=leadtime_agg_coord,
                            select_value=lead_value,
                            select_unit=leadtime_units.value,
                            realization_dim="realization",
                            spread="std",
                            plot_single_members=plot_members,
                            plot_title=plot_title,
                            title_strftime=title_strftime,
                            model_colors=comparison_colors,
                            model_linestyles=comparison_linestyles,
                            ylim=get_profile_ylim(
                                profile_ylims,
                                metric,
                                variant="absolute",
                            ),
                        )

                        n += 1

            # ==================================================
            # Combined comparison profiles
            #
            # "mlfc" in model_comparisons represents each
            # selected experiment independently.
            # ==================================================

            for (
                baseline_model,
                target_model,
            ) in model_comparisons:

                # ----------------------------------------------
                # Multiple ML experiments against common
                # baseline.
                # ----------------------------------------------

                if target_model == "mlfc":

                    if (
                        baseline_model
                        not in das_by_model
                    ):
                        continue

                    baseline_ds = (
                        das_by_model[
                            baseline_model
                        ]
                    )

                    for metric in metrics:

                        if (
                            metric
                            == "rank_histogram"
                        ):
                            continue

                        if metric not in baseline_ds:
                            continue

                        comparison_by_variant: dict[
                            str,
                            list[
                                tuple[
                                    str,
                                    xr.DataArray,
                                ]
                            ],
                        ] = {}


                        for (
                            experiment_label
                        ) in comparison_labels:

                            if (
                                experiment_label
                                not in das_by_model
                            ):
                                continue

                            target_ds = (
                                das_by_model[
                                    experiment_label
                                ]
                            )

                            if (
                                metric
                                not in target_ds
                            ):
                                continue

                            improvements = (
                                build_metric_improvements(
                                    baseline_ds,
                                    target_ds,
                                    metric=metric,
                                    baseline_model=(
                                        baseline_model
                                    ),
                                    target_model=(
                                        experiment_label
                                    ),
                                )
                            )

                            for (
                                generated_name,
                                comparison_da,
                            ) in improvements.items():

                                variant = (
                                    get_improvement_variant(
                                        generated_name
                                    )
                                )

                                comparison_by_variant.setdefault(
                                    variant,
                                    [],
                                ).append(
                                    (
                                        experiment_label,
                                        comparison_da,
                                    )
                                )

                        for (
                            variant,
                            entries,
                        ) in (
                            comparison_by_variant.items()
                        ):

                            if not entries:
                                continue

                            comparison_models = tuple(
                                label
                                for label, _
                                in entries
                            )

                            comparison_das = [
                                da
                                for _, da
                                in entries
                            ]

                            comparison_variant = (
                                f"{target_model}_vs_"
                                f"{baseline_model}_"
                                f"{variant}"
                            )

                            improvement_unit = {
                                "percentage": "%",
                                "difference": "Δ",
                                "normalized": "normalized",
                            }[variant]

                            for (
                                start_period
                            ) in leadtime_profile_periods:

                                common_path = (
                                    Path("profiles")
                                    / combined_plot_folder
                                    / comparison_name
                                    / "comparisons"
                                    / safe_label(
                                        comparison_variant
                                    )
                                    / safe_label(
                                        start_period
                                    )
                                    / (
                                        f"time_"
                                        f"{safe_label(valid_time_range)}"
                                        f"_lat_"
                                        f"{safe_label(valid_lat_range)}"
                                        f"_lon_"
                                        f"{safe_label(valid_lon_range)}"
                                    )
                                    / metric
                                    / metric_agg_mode
                                )

                                filename = (
                                    f"{common_s.var_fc}_"
                                    f"{metric}_"
                                    f"{safe_label(comparison_variant)}_"
                                    f"{leadtime_agg_mode}lt.png"
                                )

                                out_file = (
                                    common_plot_dir
                                    / common_path
                                    / filename
                                )

                                if (
                                    out_file.exists()
                                    and not regenerate_plots
                                ):
                                    continue

                                print(
                                    "Saving combined "
                                    "comparison profile "
                                    f"{out_file}"
                                )

                                plot_profile(
                                    das=comparison_das,
                                    var=common_s.var_fc,
                                    metric=metric,
                                    models=comparison_models,
                                    out_file=out_file,
                                    time_range=valid_time_range,
                                    das_member=[
                                        None
                                        for _
                                        in comparison_das
                                    ],
                                    profile_dim=leadtime_agg_coord,
                                    profile_unit=leadtime_units,
                                    select_value=start_period,
                                    select_dim=period_dim,
                                    select_unit=clim_period.value,
                                    realization_dim="realization",
                                    spread="std",
                                    plot_single_members=False,
                                    plot_title=plot_title,
                                    title_strftime=title_strftime,
                                    improvement_unit=improvement_unit,
                                    model_colors=comparison_colors,
                                    model_linestyles=comparison_linestyles,
                                    ylim=get_profile_ylim(
                                        profile_ylims,
                                        metric,
                                        variant=variant,
                                    ),
                                )

                                n += 1

                            # ----------------------------------
                            # Climatological-period profiles
                            # ----------------------------------

                            if plot_climatological_profiles:
                                climatological_comparison_das = [
                                    prepare_climatological_profile_da(
                                        da,
                                        period_dim=period_dim,
                                        clim_period=clim_period,
                                    )
                                    for da in comparison_das
                                ]

                                for (
                                    lead_value
                                ) in climatological_profile_leadtimes:

                                    common_path = (
                                        Path("profiles")
                                        / combined_plot_folder
                                        / comparison_name
                                        / "climatology"
                                        / "comparisons"
                                        / safe_label(
                                            comparison_variant
                                        )
                                        / (
                                            f"leadtime_"
                                            f"{safe_label(lead_value)}"
                                        )
                                        / (
                                            f"time_"
                                            f"{safe_label(valid_time_range)}"
                                            f"_lat_"
                                            f"{safe_label(valid_lat_range)}"
                                            f"_lon_"
                                            f"{safe_label(valid_lon_range)}"
                                        )
                                        / metric
                                        / metric_agg_mode
                                    )

                                    filename = (
                                        f"{common_s.var_fc}_"
                                        f"{metric}_"
                                        f"{safe_label(comparison_variant)}_"
                                        f"{safe_label(period_dim)}_"
                                        f"leadtime_"
                                        f"{safe_label(lead_value)}.png"
                                    )

                                    out_file = (
                                        common_plot_dir
                                        / common_path
                                        / filename
                                    )

                                    if (
                                        out_file.exists()
                                        and not regenerate_plots
                                    ):
                                        continue

                                    print(
                                        "Saving combined climatological "
                                        "comparison profile "
                                        f"{out_file}"
                                    )

                                    plot_profile(
                                        das=climatological_comparison_das,
                                        var=common_s.var_fc,
                                        metric=metric,
                                        models=comparison_models,
                                        out_file=out_file,
                                        time_range=valid_time_range,
                                        das_member=[
                                            None
                                            for _
                                            in climatological_comparison_das
                                        ],
                                        profile_dim=period_dim,
                                        profile_unit=None,
                                        select_dim=leadtime_agg_coord,
                                        select_value=lead_value,
                                        select_unit=leadtime_units.value,
                                        realization_dim="realization",
                                        spread="std",
                                        plot_single_members=False,
                                        plot_title=plot_title,
                                        title_strftime=title_strftime,
                                        improvement_unit=improvement_unit,
                                        model_colors=comparison_colors,
                                        model_linestyles=comparison_linestyles,
                                        ylim=get_profile_ylim(
                                            profile_ylims,
                                            metric,
                                            variant=variant,
                                        ),
                                    )

                                    n += 1

                # ----------------------------------------------
                # Comparison between common non-ML models,
                # e.g. FC -> clim-FC.
                # ----------------------------------------------

                else:

                    if (
                        baseline_model
                        not in das_by_model
                    ):
                        continue

                    if (
                        target_model
                        not in das_by_model
                    ):
                        continue

                    baseline_ds = (
                        das_by_model[
                            baseline_model
                        ]
                    )

                    target_ds = (
                        das_by_model[
                            target_model
                        ]
                    )

                    comparison_metrics = [
                        metric
                        for metric in metrics
                        if (
                            metric
                            != "rank_histogram"
                            and metric
                            in baseline_ds
                            and metric
                            in target_ds
                        )
                    ]

                    for metric in comparison_metrics:

                        improvements = (
                            build_metric_improvements(
                                baseline_ds,
                                target_ds,
                                metric=metric,
                                baseline_model=baseline_model,
                                target_model=target_model,
                            )
                        )

                        for (
                            comparison_model,
                            comparison_da,
                        ) in improvements.items():

                            for (
                                start_period
                            ) in leadtime_profile_periods:

                                common_path = (
                                    Path("profiles")
                                    / combined_plot_folder
                                    / comparison_name
                                    / "comparisons"
                                    / safe_label(
                                        comparison_model
                                    )
                                    / safe_label(
                                        start_period
                                    )
                                    / (
                                        f"time_"
                                        f"{safe_label(valid_time_range)}"
                                        f"_lat_"
                                        f"{safe_label(valid_lat_range)}"
                                        f"_lon_"
                                        f"{safe_label(valid_lon_range)}"
                                    )
                                    / metric
                                    / metric_agg_mode
                                )

                                filename = (
                                    f"{common_s.var_fc}_"
                                    f"{metric}_"
                                    f"{safe_label(comparison_model)}_"
                                    f"{leadtime_agg_mode}lt.png"
                                )

                                out_file = (
                                    common_plot_dir
                                    / common_path
                                    / filename
                                )

                                if (
                                    out_file.exists()
                                    and not regenerate_plots
                                ):
                                    continue

                                print(
                                    "Saving combined "
                                    "comparison profile "
                                    f"{out_file}"
                                )

                                plot_profile(
                                    das=[
                                        comparison_da
                                    ],
                                    var=common_s.var_fc,
                                    metric=metric,
                                    models=(
                                        comparison_model,
                                    ),
                                    out_file=out_file,
                                    time_range=valid_time_range,
                                    das_member=[None],
                                    profile_dim=leadtime_agg_coord,
                                    profile_unit=leadtime_units,
                                    select_value=start_period,
                                    select_dim=period_dim,
                                    select_unit=clim_period.value,
                                    realization_dim="realization",
                                    spread="std",
                                    plot_single_members=False,
                                    plot_title=plot_title,
                                    title_strftime=title_strftime,
                                    ylim=get_profile_ylim(
                                        profile_ylims,
                                        metric,
                                        variant=get_improvement_variant(
                                            comparison_model
                                        ),
                                    ),
                                )

                                n += 1

                            # ----------------------------------
                            # Climatological-period profile
                            # ----------------------------------

                            if plot_climatological_profiles:
                                climatological_comparison_da = (
                                    prepare_climatological_profile_da(
                                        comparison_da,
                                        period_dim=period_dim,
                                        clim_period=clim_period,
                                    )
                                )

                                for (
                                    lead_value
                                ) in climatological_profile_leadtimes:

                                    common_path = (
                                        Path("profiles")
                                        / combined_plot_folder
                                        / comparison_name
                                        / "climatology"
                                        / "comparisons"
                                        / safe_label(
                                            comparison_model
                                        )
                                        / (
                                            f"leadtime_"
                                            f"{safe_label(lead_value)}"
                                        )
                                        / (
                                            f"time_"
                                            f"{safe_label(valid_time_range)}"
                                            f"_lat_"
                                            f"{safe_label(valid_lat_range)}"
                                            f"_lon_"
                                            f"{safe_label(valid_lon_range)}"
                                        )
                                        / metric
                                        / metric_agg_mode
                                    )

                                    filename = (
                                        f"{common_s.var_fc}_"
                                        f"{metric}_"
                                        f"{safe_label(comparison_model)}_"
                                        f"{safe_label(period_dim)}_"
                                        f"leadtime_"
                                        f"{safe_label(lead_value)}.png"
                                    )

                                    out_file = (
                                        common_plot_dir
                                        / common_path
                                        / filename
                                    )

                                    if (
                                        out_file.exists()
                                        and not regenerate_plots
                                    ):
                                        continue

                                    print(
                                        "Saving combined climatological "
                                        "comparison profile "
                                        f"{out_file}"
                                    )

                                    plot_profile(
                                        das=[
                                            climatological_comparison_da
                                        ],
                                        var=common_s.var_fc,
                                        metric=metric,
                                        models=(
                                            comparison_model,
                                        ),
                                        out_file=out_file,
                                        time_range=valid_time_range,
                                        das_member=[None],
                                        profile_dim=period_dim,
                                        profile_unit=None,
                                        select_dim=leadtime_agg_coord,
                                        select_value=lead_value,
                                        select_unit=leadtime_units.value,
                                        realization_dim="realization",
                                        spread="std",
                                        plot_single_members=False,
                                        plot_title=plot_title,
                                        title_strftime=title_strftime,
                                        ylim=get_profile_ylim(
                                            profile_ylims,
                                            metric,
                                            variant=get_improvement_variant(
                                                comparison_model
                                            ),
                                        ),
                                    )

                                    n += 1

    print(
        f"Done. Saved {n} plots."
    )

if __name__ == "__main__":
    main()
